name: Build and Deploy Monolith

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/hackatona_2024_frontend:production
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Copy Docker Compose file to server
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            port: 22
            source: './docker-compose.yml'
            target: '/root/apps/hackatona_2024_front/'

        - name: Run image
          uses: appleboy/ssh-action@v0.1.6
          with:
              host: ${{ secrets.HOST_IP }}
              username: ${{ secrets.HOST_USERNAME }}
              password: ${{ secrets.HOST_PASSWORD }}
              port: 22
              script: |
                cd /root/apps/hackatona_2024_front
                docker stack deploy -c docker-compose.yml --with-registry-auth prod